# Generated by Django 6.0.2 on 2026-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_submission_text_answer_submission_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='marks',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
